# Generated by Django 6.0.2 on 2026-02-12 03:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hub_team_id", models.CharField(db_index=True, max_length=50)),
                ("hub_client_id", models.CharField(db_index=True, max_length=50)),
                ("phone_e164", models.CharField(db_index=True, max_length=20)),
                ("display_name", models.CharField(max_length=255)),
                ("preferred_channel", models.CharField(default="whatsapp", max_length=20)),
                ("timezone", models.CharField(default="America/New_York", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("hub_team_id", "hub_client_id")},
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("channel", models.CharField(default="whatsapp", max_length=20)),
                (
                    "consent_type",
                    models.CharField(
                        choices=[("opt_in", "Opt In"), ("opt_out", "Opt Out"), ("revoked", "Revoked")], max_length=30
                    ),
                ),
                (
                    "consent_source",
                    models.CharField(
                        choices=[
                            ("web_form", "Web Form"),
                            ("whatsapp_reply", "WhatsApp Reply"),
                            ("api", "API"),
                            ("manual", "Manual"),
                        ],
                        max_length=50,
                    ),
                ),
                ("consented_at", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="consents", to="core.contactprofile"
                    ),
                ),
            ],
            options={
                "ordering": ["-consented_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("channel", models.CharField(default="whatsapp", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("waiting_reply", "Waiting for Reply"),
                            ("timed_out", "Timed Out"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("current_state", models.CharField(default="initial", max_length=50)),
                ("state_data", models.JSONField(blank=True, default=dict)),
                ("context_type", models.CharField(blank=True, max_length=50)),
                ("context_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("context_data", models.JSONField(blank=True, default=dict)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                ("timeout_minutes", models.PositiveIntegerField(default=1440)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="core.contactprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "direction",
                    models.CharField(choices=[("inbound", "Inbound"), ("outbound", "Outbound")], max_length=10),
                ),
                ("body", models.TextField()),
                ("channel_message_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("template_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
