# Generated by Django 6.0.2 on 2026-02-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_telegram_chat_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contactprofile",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="contactprofile",
            name="contact_type",
            field=models.CharField(
                choices=[("client", "Client"), ("accountant", "Accountant")], default="client", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="contactprofile",
            name="hub_client_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="contactprofile",
            name="phone_e164",
            field=models.CharField(blank=True, db_index=True, default="", max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="contactprofile",
            unique_together={("hub_team_id", "hub_client_id", "contact_type")},
        ),
    ]
